package fpc.aoc.day23;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

public class Day23Test {

    public static final String TEST_INPUT = """
        ..............
        ..............
        .......#......
        .....###.#....
        ...#...#.#....
        ....#...##....
        ...#.###......
        ...##.#.##....
        ....#..#......
        ..............
        ..............
        ..............
            """;

    @Test
    public void testPart1() {
        final var actual = new Day23Part1Solver().createProblem(TEST_INPUT).solve();
        Assertions.assertEquals(110,actual);
    }

    @Test
    public void testPart2() {
        final var actual = new Day23Part2Solver().createProblem(TEST_INPUT).solve();
        Assertions.assertEquals(20,actual);
    }


}
