@startdot
graph valves {
DD [label="DD\n8"]
LL [label="LL\n5"]
LY [label="LY\n21"]
UC [label="UC\n25"]
QD [label="QD\n14"]
IR [label="IR\n9"]
EU [label="EU\n19"]
VH [label="VH\n10"]
NJ [label="NJ\n6"]
OC [label="OC\n18"]
WL [label="WL\n12"]
KH [label="KH\n13"]
SS [label="SS\n17"]
CP [label="CP\n24"]
PC [label="PC\n22"]
IR -- LL [label="2"]
CP -- WL [label="2"]
IR -- LY [label="2"]
DD -- LL [label="2"]
NJ -- VH [label="2"]
OC -- VH [label="3"]
LY -- QD [label="2"]
IR -- VH [label="4"]
DD -- IR [label="4"]
CP -- UC [label="3"]
SS -- UC [label="3"]
CP -- LY [label="3"]
LL -- VH [label="3"]
DD -- VH [label="4"]
IR -- NJ [label="3"]
DD -- EU [label="2"]
QD -- WL [label="2"]
NJ -- SS [label="2"]
LL -- NJ [label="3"]
DD -- NJ [label="5"]
KH -- WL [label="3"]
IR -- SS [label="2"]
LY -- WL [label="2"]
KH -- PC [label="2"]
DD -- SS [label="3"]
}
@enddot